// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Access related settings for IAP protected apps.
public struct AccessSettings: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. GCIP claims and endpoint configurations for 3p identity
  /// providers.
  public var gcipSettings: GcipSettings? = nil

  /// Optional. Configuration to allow cross-origin requests via IAP.
  public var corsSettings: CorsSettings? = nil

  /// Optional. Settings to configure IAP's OAuth behavior.
  public var oauthSettings: OAuthSettings? = nil

  /// Optional. Settings to configure reauthentication policies in IAP.
  public var reauthSettings: ReauthSettings? = nil

  /// Optional. Settings to configure and enable allowed domains.
  public var allowedDomainsSettings: AllowedDomainsSettings? = nil

  /// Optional. Settings to configure the workforce identity federation,
  /// including workforce pools and OAuth 2.0 settings.
  public var workforceIdentitySettings: WorkforceIdentitySettings? = nil

  /// Optional. Identity sources that IAP can use to authenticate the end user.
  /// Only one identity source can be configured.
  public var identitySources: [AccessSettings.IdentitySource] = []

  /// Initialize a new instance of `AccessSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AccessSettings().with { $0.gcipSettings = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Types of identity source supported by IAP.
  public enum IdentitySource: Codable, Equatable, Sendable {
    /// IdentitySource Unspecified.
    /// When selected, IAP relies on which identity settings are fully configured
    /// to redirect the traffic to. The precedence order is
    /// WorkforceIdentitySettings > GcipSettings. If none is set, default to use
    /// Google identity.
    case unspecified
    /// Use external identities set up on Google Cloud Workforce Identity
    /// Federation.
    case workforceIdentityFederation
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .workforceIdentityFederation: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "IDENTITY_SOURCE_UNSPECIFIED"
      case .workforceIdentityFederation: return "WORKFORCE_IDENTITY_FEDERATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:IdentitySource/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "IDENTITY_SOURCE_UNSPECIFIED": self = .unspecified
      case "WORKFORCE_IDENTITY_FEDERATION": self = .workforceIdentityFederation
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:IdentitySource/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 3: self = .workforceIdentityFederation
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .workforceIdentityFederation: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.iap.v1.AccessSettings"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
