// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Wrapper over application specific settings for IAP.
public struct ApplicationSettings: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Settings to configure IAP's behavior for a service mesh.
  public var csmSettings: CsmSettings? = nil

  /// Optional. Customization for Access Denied page.
  public var accessDeniedPageSettings: AccessDeniedPageSettings? = nil

  /// The Domain value to set for cookies generated by IAP. This value is not
  /// validated by the API, but will be ignored at runtime if invalid.
  public var cookieDomain: GoogleCloudWKT.StringValue? = nil

  /// Optional. Settings to configure attribute propagation.
  public var attributePropagationSettings: AttributePropagationSettings? = nil

  /// Initialize a new instance of `ApplicationSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApplicationSettings().with { $0.csmSettings = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.iap.v1.ApplicationSettings"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
