// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request to CreateTunnelDestGroup.
public struct CreateTunnelDestGroupRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Google Cloud Project ID and location.
  /// In the following format:
  /// `projects/{project_number/id}/iap_tunnel/locations/{location}`.
  public var parent: Swift.String = Swift.String()

  /// Required. The TunnelDestGroup to create.
  public var tunnelDestGroup: TunnelDestGroup? = nil

  /// Required. The ID to use for the TunnelDestGroup, which becomes the final
  /// component of the resource name.
  ///
  /// This value must be 4-63 characters, and valid characters
  /// are `[a-z]-`.
  public var tunnelDestGroupId: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateTunnelDestGroupRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateTunnelDestGroupRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.iap.v1.CreateTunnelDestGroupRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
