// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Allows customers to configure tenant IDs for a Cloud Identity Platform (GCIP)
/// instance for each application.
public struct GcipSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. GCIP tenant IDs that are linked to the IAP resource. `tenant_ids`
  /// could be a string beginning with a number character to indicate
  /// authenticating with GCIP tenant flow, or in the format of
  /// `_<ProjectNumber>` to indicate authenticating with GCIP agent flow. If
  /// agent flow is used, `tenant_ids` should only contain one single element,
  /// while for tenant flow, `tenant_ids` can contain multiple elements.
  public var tenantIds: [Swift.String] = []

  /// Login page URI associated with the GCIP tenants.
  /// Typically, all resources within the same project share the same login page,
  /// though it could be overridden at the sub resource level.
  public var loginPageUri: GoogleCloudWkt.StringValue? = nil

  /// Initialize a new instance of `GcipSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcipSettings().with { $0.tenantIds = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.iap.v1.GcipSettings"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
