// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleIAMV1
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  class IdentityAwareProxyAdminServiceTransport: IdentityAwareProxyAdminServiceStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://iap.googleapis.com",
      )
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.resource as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.resource' is not set or is empty")
        }
        return "/v1/\(pathVariable0):setIamPolicy"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleIAMV1.Policy.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.resource as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.resource' is not set or is empty")
        }
        return "/v1/\(pathVariable0):getIamPolicy"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleIAMV1.Policy.self, timeout: options.attemptTimeout
      ).get()
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.resource as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.resource' is not set or is empty")
        }
        return "/v1/\(pathVariable0):testIamPermissions"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleIAMV1.TestIamPermissionsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getIapSettings(
      request: GetIapSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.IapSettings {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):iapSettings"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudIAPV1.IapSettings.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateIapSettings(
      request: UpdateIapSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.IapSettings {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.iapSettings.map({ $0.name }), !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.iap_settings.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):iapSettings"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      if let body = request.iapSettings {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudIAPV1.IapSettings.self, timeout: options.attemptTimeout
      ).get()
    }

    public func validateIapAttributeExpression(
      request: ValidateIapAttributeExpressionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.ValidateIapAttributeExpressionResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):validateAttributeExpression"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.expression, prefix: "expression"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudIAPV1.ValidateIapAttributeExpressionResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func listTunnelDestGroups(
      request: ListTunnelDestGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.ListTunnelDestGroupsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/destGroups"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudIAPV1.ListTunnelDestGroupsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createTunnelDestGroup(
      request: CreateTunnelDestGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.TunnelDestGroup {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/destGroups"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(
        contentsOf: try encoder.encode(request.tunnelDestGroupId, prefix: "tunnelDestGroupId"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      if let body = request.tunnelDestGroup {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudIAPV1.TunnelDestGroup.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getTunnelDestGroup(
      request: GetTunnelDestGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.TunnelDestGroup {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudIAPV1.TunnelDestGroup.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteTunnelDestGroup(
      request: DeleteTunnelDestGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateTunnelDestGroup(
      request: UpdateTunnelDestGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.TunnelDestGroup {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.tunnelDestGroup.map({ $0.name }), !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.tunnel_dest_group.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      if let body = request.tunnelDestGroup {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudIAPV1.TunnelDestGroup.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
