// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleIAMV1
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class IdentityAwareProxyAdminServiceLogging: IdentityAwareProxyAdminServiceStub {
    let inner: any IdentityAwareProxyAdminServiceStub
    let logger: Logger

    public init(_ inner: any IdentityAwareProxyAdminServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-iap-v1"
      logger[metadataKey: "gcp.client.service"] = "iap"
      logger[metadataKey: "gcp.experimental.swift.client"] = "IdentityAwareProxyAdminService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func getIapSettings(
      request: GetIapSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.IapSettings {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIapSettings",
        action: {
          (r: GetIapSettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudIAPV1.IapSettings
          in
          return try await self.inner.getIapSettings(request: r, options: o)
        })
    }

    public func updateIapSettings(
      request: UpdateIapSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.IapSettings {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateIapSettings",
        action: {
          (r: UpdateIapSettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudIAPV1.IapSettings
          in
          return try await self.inner.updateIapSettings(request: r, options: o)
        })
    }

    public func validateIapAttributeExpression(
      request: ValidateIapAttributeExpressionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.ValidateIapAttributeExpressionResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "validateIapAttributeExpression",
        action: {
          (r: ValidateIapAttributeExpressionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudIAPV1.ValidateIapAttributeExpressionResponse
          in
          return try await self.inner.validateIapAttributeExpression(request: r, options: o)
        })
    }

    public func listTunnelDestGroups(
      request: ListTunnelDestGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.ListTunnelDestGroupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTunnelDestGroups",
        action: {
          (r: ListTunnelDestGroupsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudIAPV1.ListTunnelDestGroupsResponse
          in
          return try await self.inner.listTunnelDestGroups(request: r, options: o)
        })
    }

    public func createTunnelDestGroup(
      request: CreateTunnelDestGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.TunnelDestGroup {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTunnelDestGroup",
        action: {
          (r: CreateTunnelDestGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudIAPV1.TunnelDestGroup
          in
          return try await self.inner.createTunnelDestGroup(request: r, options: o)
        })
    }

    public func getTunnelDestGroup(
      request: GetTunnelDestGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.TunnelDestGroup {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTunnelDestGroup",
        action: {
          (r: GetTunnelDestGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudIAPV1.TunnelDestGroup
          in
          return try await self.inner.getTunnelDestGroup(request: r, options: o)
        })
    }

    public func deleteTunnelDestGroup(
      request: DeleteTunnelDestGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTunnelDestGroup",
        action: {
          (r: DeleteTunnelDestGroupRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteTunnelDestGroup(request: r, options: o)
        })
    }

    public func updateTunnelDestGroup(
      request: UpdateTunnelDestGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.TunnelDestGroup {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTunnelDestGroup",
        action: {
          (r: UpdateTunnelDestGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudIAPV1.TunnelDestGroup
          in
          return try await self.inner.updateTunnelDestGroup(request: r, options: o)
        })
    }
  }
}
