// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleCloudGax

extension Clients {
  protocol IdentityAwareProxyOAuthServiceStub: Sendable {
    func listBrands(
      request: ListBrandsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.ListBrandsResponse

    func createBrand(
      request: CreateBrandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.Brand

    func getBrand(
      request: GetBrandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.Brand

    func createIdentityAwareProxyClient(
      request: CreateIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient

    func listIdentityAwareProxyClients(
      request: ListIdentityAwareProxyClientsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.ListIdentityAwareProxyClientsResponse

    func getIdentityAwareProxyClient(
      request: GetIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient

    func resetIdentityAwareProxyClientSecret(
      request: ResetIdentityAwareProxyClientSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient

    func deleteIdentityAwareProxyClient(
      request: DeleteIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
