// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// API to programmatically create, list and retrieve Identity Aware Proxy (IAP)
/// OAuth brands; and create, retrieve, delete and reset-secret of IAP OAuth
/// clients.
///
/// @Snippet(path: "IdentityAwareProxyOAuthServiceQuickstart")
public class IdentityAwareProxyOAuthServiceClient: Clients.IdentityAwareProxyOAuthServiceProtocol {
  let inner: any Clients.IdentityAwareProxyOAuthServiceStub

  /// Creates a new `IdentityAwareProxyOAuthServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.IdentityAwareProxyOAuthServiceStub =
      try Clients.IdentityAwareProxyOAuthServiceTransport(options)
    inner = Clients.IdentityAwareProxyOAuthServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.IdentityAwareProxyOAuthServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists the existing brands for the project.
  ///
  /// @Snippet(path: "IdentityAwareProxyOAuthService_ListBrands")
  public func listBrands(
    request: ListBrandsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.ListBrandsResponse {
    try await self.inner.listBrands(request: request, options: options)
  }

  /// Constructs a new OAuth brand for the project if one does not exist.
  /// The created brand is "internal only", meaning that OAuth clients created
  /// under it only accept requests from users who belong to the same Google
  /// Workspace organization as the project. The brand is created in an
  /// un-reviewed status. NOTE: The "internal only" status can be manually
  /// changed in the Google Cloud Console. Requires that a brand does not already
  /// exist for the project, and that the specified support email is owned by the
  /// caller.
  ///
  /// @Snippet(path: "IdentityAwareProxyOAuthService_CreateBrand")
  public func createBrand(
    request: CreateBrandRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.Brand {
    try await self.inner.createBrand(request: request, options: options)
  }

  /// Retrieves the OAuth brand of the project.
  ///
  /// @Snippet(path: "IdentityAwareProxyOAuthService_GetBrand")
  public func getBrand(
    request: GetBrandRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.Brand {
    try await self.inner.getBrand(request: request, options: options)
  }

  /// Creates an Identity Aware Proxy (IAP) OAuth client. The client is owned
  /// by IAP. Requires that the brand for the project exists and that it is
  /// set for internal-only use.
  ///
  /// @Snippet(path: "IdentityAwareProxyOAuthService_CreateIdentityAwareProxyClient")
  public func createIdentityAwareProxyClient(
    request: CreateIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient {
    try await self.inner.createIdentityAwareProxyClient(request: request, options: options)
  }

  /// Lists the existing clients for the brand.
  ///
  /// @Snippet(path: "IdentityAwareProxyOAuthService_ListIdentityAwareProxyClients")
  public func listIdentityAwareProxyClients(
    request: ListIdentityAwareProxyClientsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.ListIdentityAwareProxyClientsResponse {
    try await self.inner.listIdentityAwareProxyClients(request: request, options: options)
  }

  /// Lists the existing clients for the brand.
  ///
  /// @Snippet(path: "IdentityAwareProxyOAuthService_ListIdentityAwareProxyClients")
  public func listIdentityAwareProxyClients(
    byItem: ListIdentityAwareProxyClientsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<IdentityAwareProxyClient, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudIAPV1.ListIdentityAwareProxyClientsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listIdentityAwareProxyClients(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Retrieves an Identity Aware Proxy (IAP) OAuth client.
  /// Requires that the client is owned by IAP.
  ///
  /// @Snippet(path: "IdentityAwareProxyOAuthService_GetIdentityAwareProxyClient")
  public func getIdentityAwareProxyClient(
    request: GetIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient {
    try await self.inner.getIdentityAwareProxyClient(request: request, options: options)
  }

  /// Resets an Identity Aware Proxy (IAP) OAuth client secret. Useful if the
  /// secret was compromised. Requires that the client is owned by IAP.
  ///
  /// @Snippet(path: "IdentityAwareProxyOAuthService_ResetIdentityAwareProxyClientSecret")
  public func resetIdentityAwareProxyClientSecret(
    request: ResetIdentityAwareProxyClientSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient {
    try await self.inner.resetIdentityAwareProxyClientSecret(request: request, options: options)
  }

  /// Deletes an Identity Aware Proxy (IAP) OAuth client. Useful for removing
  /// obsolete clients, managing the number of clients in a given project, and
  /// cleaning up after tests. Requires that the client is owned by IAP.
  ///
  /// @Snippet(path: "IdentityAwareProxyOAuthService_DeleteIdentityAwareProxyClient")
  public func deleteIdentityAwareProxyClient(
    request: DeleteIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteIdentityAwareProxyClient(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `IdentityAwareProxyOAuthServiceClient`.
  ///
  /// To mock `IdentityAwareProxyOAuthServiceClient` change your functions to receive
  /// `some IdentityAwareProxyOAuthServiceProtocol` or `any IdentityAwareProxyOAuthServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol IdentityAwareProxyOAuthServiceProtocol {
    /// See `IdentityAwareProxyOAuthServiceClient.listBrands`.
    func listBrands(request: ListBrandsRequest) async throws -> GoogleCloudIAPV1.ListBrandsResponse

    /// See `IdentityAwareProxyOAuthServiceClient.createBrand`.
    func createBrand(request: CreateBrandRequest) async throws -> GoogleCloudIAPV1.Brand

    /// See `IdentityAwareProxyOAuthServiceClient.getBrand`.
    func getBrand(request: GetBrandRequest) async throws -> GoogleCloudIAPV1.Brand

    /// See `IdentityAwareProxyOAuthServiceClient.createIdentityAwareProxyClient`.
    func createIdentityAwareProxyClient(request: CreateIdentityAwareProxyClientRequest) async throws
      -> GoogleCloudIAPV1.IdentityAwareProxyClient

    /// See `IdentityAwareProxyOAuthServiceClient.listIdentityAwareProxyClients`.
    func listIdentityAwareProxyClients(request: ListIdentityAwareProxyClientsRequest) async throws
      -> GoogleCloudIAPV1.ListIdentityAwareProxyClientsResponse

    /// See `IdentityAwareProxyOAuthServiceClient.listIdentityAwareProxyClients`.
    func listIdentityAwareProxyClients(
      byItem: ListIdentityAwareProxyClientsRequest
    ) throws -> any AsyncSequence<IdentityAwareProxyClient, Swift.Error>

    /// See `IdentityAwareProxyOAuthServiceClient.getIdentityAwareProxyClient`.
    func getIdentityAwareProxyClient(request: GetIdentityAwareProxyClientRequest) async throws
      -> GoogleCloudIAPV1.IdentityAwareProxyClient

    /// See `IdentityAwareProxyOAuthServiceClient.resetIdentityAwareProxyClientSecret`.
    func resetIdentityAwareProxyClientSecret(request: ResetIdentityAwareProxyClientSecretRequest)
      async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient

    /// See `IdentityAwareProxyOAuthServiceClient.deleteIdentityAwareProxyClient`.
    func deleteIdentityAwareProxyClient(request: DeleteIdentityAwareProxyClientRequest) async throws

    /// See `IdentityAwareProxyOAuthServiceClient.listBrands`.
    func listBrands(
      request: ListBrandsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.ListBrandsResponse

    /// See `IdentityAwareProxyOAuthServiceClient.createBrand`.
    func createBrand(
      request: CreateBrandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.Brand

    /// See `IdentityAwareProxyOAuthServiceClient.getBrand`.
    func getBrand(
      request: GetBrandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.Brand

    /// See `IdentityAwareProxyOAuthServiceClient.createIdentityAwareProxyClient`.
    func createIdentityAwareProxyClient(
      request: CreateIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient

    /// See `IdentityAwareProxyOAuthServiceClient.listIdentityAwareProxyClients`.
    func listIdentityAwareProxyClients(
      request: ListIdentityAwareProxyClientsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.ListIdentityAwareProxyClientsResponse

    /// See `IdentityAwareProxyOAuthServiceClient.listIdentityAwareProxyClients`.
    func listIdentityAwareProxyClients(
      byItem: ListIdentityAwareProxyClientsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<IdentityAwareProxyClient, Swift.Error>

    /// See `IdentityAwareProxyOAuthServiceClient.getIdentityAwareProxyClient`.
    func getIdentityAwareProxyClient(
      request: GetIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient

    /// See `IdentityAwareProxyOAuthServiceClient.resetIdentityAwareProxyClientSecret`.
    func resetIdentityAwareProxyClientSecret(
      request: ResetIdentityAwareProxyClientSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient

    /// See `IdentityAwareProxyOAuthServiceClient.deleteIdentityAwareProxyClient`.
    func deleteIdentityAwareProxyClient(
      request: DeleteIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.IdentityAwareProxyOAuthServiceProtocol {
  public func listBrands(request: ListBrandsRequest) async throws
    -> GoogleCloudIAPV1.ListBrandsResponse
  {
    try await self.listBrands(request: request, options: .init())
  }

  public func listBrands(
    request: ListBrandsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.ListBrandsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createBrand(request: CreateBrandRequest) async throws -> GoogleCloudIAPV1.Brand {
    try await self.createBrand(request: request, options: .init())
  }

  public func createBrand(
    request: CreateBrandRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.Brand {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getBrand(request: GetBrandRequest) async throws -> GoogleCloudIAPV1.Brand {
    try await self.getBrand(request: request, options: .init())
  }

  public func getBrand(
    request: GetBrandRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.Brand {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createIdentityAwareProxyClient(request: CreateIdentityAwareProxyClientRequest)
    async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient
  {
    try await self.createIdentityAwareProxyClient(request: request, options: .init())
  }

  public func createIdentityAwareProxyClient(
    request: CreateIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listIdentityAwareProxyClients(request: ListIdentityAwareProxyClientsRequest)
    async throws -> GoogleCloudIAPV1.ListIdentityAwareProxyClientsResponse
  {
    try await self.listIdentityAwareProxyClients(request: request, options: .init())
  }

  public func listIdentityAwareProxyClients(
    request: ListIdentityAwareProxyClientsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.ListIdentityAwareProxyClientsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listIdentityAwareProxyClients(
    byItem: ListIdentityAwareProxyClientsRequest
  ) throws -> any AsyncSequence<IdentityAwareProxyClient, Swift.Error> {
    try self.listIdentityAwareProxyClients(byItem: byItem, options: .init())
  }

  public func listIdentityAwareProxyClients(
    byItem: ListIdentityAwareProxyClientsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<IdentityAwareProxyClient, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudIAPV1.ListIdentityAwareProxyClientsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getIdentityAwareProxyClient(request: GetIdentityAwareProxyClientRequest) async throws
    -> GoogleCloudIAPV1.IdentityAwareProxyClient
  {
    try await self.getIdentityAwareProxyClient(request: request, options: .init())
  }

  public func getIdentityAwareProxyClient(
    request: GetIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func resetIdentityAwareProxyClientSecret(
    request: ResetIdentityAwareProxyClientSecretRequest
  ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient {
    try await self.resetIdentityAwareProxyClientSecret(request: request, options: .init())
  }

  public func resetIdentityAwareProxyClientSecret(
    request: ResetIdentityAwareProxyClientSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteIdentityAwareProxyClient(request: DeleteIdentityAwareProxyClientRequest)
    async throws
  {
    try await self.deleteIdentityAwareProxyClient(request: request, options: .init())
  }

  public func deleteIdentityAwareProxyClient(
    request: DeleteIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
