// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class IdentityAwareProxyOAuthServiceRetry: IdentityAwareProxyOAuthServiceStub {
    let inner: any IdentityAwareProxyOAuthServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(
      _ inner: any IdentityAwareProxyOAuthServiceStub, options: GoogleCloudGax.ClientOptions
    ) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listBrands(
      request: ListBrandsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.ListBrandsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBrandsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudIAPV1.ListBrandsResponse
          in
          return try await self.inner.listBrands(request: r, options: o)
        })
    }

    public func createBrand(
      request: CreateBrandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.Brand {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateBrandRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudIAPV1.Brand
          in
          return try await self.inner.createBrand(request: r, options: o)
        })
    }

    public func getBrand(
      request: GetBrandRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.Brand {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBrandRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudIAPV1.Brand
          in
          return try await self.inner.getBrand(request: r, options: o)
        })
    }

    public func createIdentityAwareProxyClient(
      request: CreateIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateIdentityAwareProxyClientRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudIAPV1.IdentityAwareProxyClient
          in
          return try await self.inner.createIdentityAwareProxyClient(request: r, options: o)
        })
    }

    public func listIdentityAwareProxyClients(
      request: ListIdentityAwareProxyClientsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.ListIdentityAwareProxyClientsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListIdentityAwareProxyClientsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudIAPV1.ListIdentityAwareProxyClientsResponse
          in
          return try await self.inner.listIdentityAwareProxyClients(request: r, options: o)
        })
    }

    public func getIdentityAwareProxyClient(
      request: GetIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetIdentityAwareProxyClientRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudIAPV1.IdentityAwareProxyClient
          in
          return try await self.inner.getIdentityAwareProxyClient(request: r, options: o)
        })
    }

    public func resetIdentityAwareProxyClientSecret(
      request: ResetIdentityAwareProxyClientSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ResetIdentityAwareProxyClientSecretRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudIAPV1.IdentityAwareProxyClient
          in
          return try await self.inner.resetIdentityAwareProxyClientSecret(request: r, options: o)
        })
    }

    public func deleteIdentityAwareProxyClient(
      request: DeleteIdentityAwareProxyClientRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteIdentityAwareProxyClientRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteIdentityAwareProxyClient(request: r, options: o)
        })
    }
  }
}
