// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for OAuth login&consent flow behavior as well as for OAuth
/// Credentials.
public struct OAuthSettings: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Domain hint to send as hd=? parameter in OAuth request flow. Enables
  /// redirect to primary IDP by skipping Google's login screen.
  /// https://developers.google.com/identity/protocols/OpenIDConnect#hd-param
  /// Note: IAP does not verify that the id token's hd claim matches this value
  /// since access behavior is managed by IAM policies.
  public var loginHint: GoogleCloudWKT.StringValue? = nil

  /// Optional. OAuth 2.0 client ID used in the OAuth flow.
  /// This allows for client sharing. The risks of client sharing
  /// are outlined here:
  /// https://cloud.google.com/iap/docs/sharing-oauth-clients#risks.
  public var clientId: GoogleCloudWKT.StringValue? = nil

  /// Optional. Input only. OAuth secret paired with client ID.
  public var clientSecret: GoogleCloudWKT.StringValue? = nil

  /// Output only. OAuth secret SHA256 paired with client ID.
  public var clientSecretSha256: GoogleCloudWKT.StringValue? = nil

  /// Optional. List of client ids allowed to use IAP programmatically.
  public var programmaticClients: [Swift.String] = []

  /// Initialize a new instance of `OAuthSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OAuthSettings().with { $0.loginHint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.iap.v1.OAuthSettings"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
